CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS jobs (
  id UUID PRIMARY KEY,
  type VARCHAR NOT NULL,
  payload JSONB NOT NULL,
  run_at TIMESTAMPTZ NOT NULL,
  status VARCHAR NOT NULL
);
